# Generated by Django 5.1.3 on 2025-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('short_description', models.CharField(help_text='Short summary shown on project cards', max_length=300)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies (e.g. Django, PostgreSQL, Docker)', max_length=300)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Live project URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this project prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
