# Generated by Django 6.0 on 2026-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectimage_caption_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(help_text='Path inside static folder, e.g. images/projects/demo.jpg', max_length=255),
        ),
    ]
