# Generated by Django 6.0 on 2026-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.CharField(help_text='Static path, e.g. images/projects/gallery/demo-1.jpg', max_length=255),
        ),
    ]
