# Generated by Django 5.1.3 on 2025-12-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name shown in hero section', max_length=100)),
                ('title', models.CharField(help_text='Main heading (e.g. Backend Developer)', max_length=200)),
                ('subtitle', models.TextField(help_text='Short description below the title')),
                ('primary_cta_text', models.CharField(default='View Projects', max_length=50)),
                ('secondary_cta_text', models.CharField(default='Contact Me', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
