# Generated by Django 6.0 on 2026-01-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('role', models.CharField(help_text='Job title / role', max_length=200)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave empty if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently working here?')),
                ('description', models.TextField(help_text='Responsibilities / achievements')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower comes first)')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
