# Generated by Django 6.0 on 2026-01-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='order',
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
