# Generated by Django 5.1.3 on 2025-12-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name (e.g. Django, PostgreSQL)', max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('tools', 'Tools'), ('devops', 'DevOps')], help_text='Skill category', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Optional icon class or emoji (e.g. 🐍)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of skills')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
